%makeSexp.m
global Sexp
load zubs\ztmp\DATmonitor.mat
Sexp.col.BLK=[0 0 0]; Sexp.col.WHT=255*[1 1 1]; Sexp.col.GRY= Sexp.col.WHT/3;
Sexp.col.RED=255*[.7 .3 .2]; Sexp.col.GRN=255*[.7 .3 .3]; Sexp.col.BLU=255*[.3 .4 .8];
Sexp.Scol=[.7*Sexp.col.WHT; Sexp.col.BLK; Sexp.col.GRY; Sexp.col.BLK]; Sexp.Sr=[13; 13-.7; 7.5; 2.5];
Sexp.Tcol=[Sexp.col.BLU]; Sexp.Tr=(5); %Making Start and Target identical will make it look like start jumps to target position
Sexp.FBcol=cell(2,1); 
Sexp.FBcol{2}=[Sexp.col.BLU; Sexp.col.BLK]; %Hit
Sexp.FBcol{1}=[Sexp.col.GRY; Sexp.col.BLK]; %Miss
Sexp.EPcol=.8*Sexp.col.WHT; Sexp.EPr=3;
Sexp.EYEcol=Sexp.col.RED; 
Sexp.Fcol=.725*Sexp.col.WHT; Sexp.Fr=2.5;
Sexp.FBflag=1;

Sexp.MMxy=10*[CMx CMy];
Sexp.mm2pixVALS=Sexp.wRect(3:4)./Sexp.MMxy; Sexp.pix2mmVALS=Sexp.MMxy./Sexp.wRect(3:4);  
Sexp.eqs.mm2pix='@(mmin) [Sexp.mm2pixVALS(1)*mmin(:,1)+Sexp.x0 -Sexp.mm2pixVALS(2)*mmin(:,end)+Sexp.y0];';
Sexp.eqs.mm2pix0='@(mmin) [mmin(:,1)*Sexp.mm2pixVALS(1) mmin(:,end)*Sexp.mm2pixVALS(2)];';
Sexp.eqs.pix2mm='@(pixin) [(pixin(:,1)-Sexp.x0)*Sexp.pix2mmVALS(1) -(pixin(:,end)-Sexp.y0)*Sexp.pix2mmVALS(2)];';
Sexp.eqs.deg2pix='@(degin) Sexp.Dz.*tan(degin).*mean(Sexp.wRect(3:4))./mean(Sexp.MMxy);';
Sexp.eqs.screen2pix='@(screenin) [screenin(:,1)*Sexp.wRect(3) screenin(:,end)*Sexp.wRect(4)];';
Sexp.eqs.pix2screen='@(pixin) [pixin(:,1)./Sexp.wRect(3) pixin(:,end)./Sexp.wRect(4)];';
Sexp.eqs.screen2mm='@(screenin) [(screenin(:,1)-.5)*Sexp.MMxy(1) -(screenin(:,end)-.5)*Sexp.MMxy(2)];';
Sexp.eqs.pix2mm0='@(pixin) [pixin(:,1)*Sexp.pix2mmVALS(1) -(pixin(:,end)*Sexp.pix2mmVALS(2))];';
Sexp.eqs.V='@(Vin) sqrt(sum(Vin.^2,2));';
Sexp.eqs.Evel='@(Ein,Tin) sum(diff(Ein,1).^2,2)./diff(Tin,1);';
Sexp.FNlist={'mm2pix','mm2pix0','pix2mm','deg2pix','screen2pix','pix2screen','screen2mm','pix2mm0','V','Evel'};
Sexp.eqs.eqs=['for n=1:length(Sexp.FNlist), eval([''Sexp. (Sexp.FNlist{n}) = eval(Sexp.eqs.(Sexp.FNlist{n})) '']); end'];
eval(Sexp.eqs.eqs)

% no longer needed; generated by eval(Sexp.eqs.eqs)
% Sexp.mm2pix=@(mmin) [mm2pixVALS(1)*mmin(:,1)+Sexp.x0 -mm2pixVALS(2)*mmin(:,end)+Sexp.y0];
% Sexp.mm2pix0=@(mmin) [mmin(:,1)*mm2pixVALS(1) mmin(:,end)*mm2pixVALS(2)];
% Sexp.pix2mm=@(pixin) [(pixin(:,1)-Sexp.x0)*Sexp.pix2mmVALS(1) -(pixin(:,end)-Sexp.y0)*Sexp.pix2mmVALS(2)];
% Sexp.screen2pix=@(screenin) [screenin(:,1)*Sexp.wRect(3) screenin(:,end)*Sexp.wRect(4)];
% Sexp.pix2screen=@(pixin) [pixin(:,1)./Sexp.wRect(3) pixin(:,end)./Sexp.wRect(4)];
% Sexp.screen2mm=@(screenin) [(screenin(:,1)-.5)*Sexp.MMxy(1) -(screenin(:,end)-.5)*Sexp.MMxy(2)];
% Sexp.pix2mm0=@(pixin) [pixin(:,1)*Sexp.pix2mmVALS(1) -(pixin(:,end)*Sexp.pix2mmVALS(2))];

Sexp.jF=0;
Sexp.z0=0;
Sexp.Zcrit=7;
Sexp.corrok=1;

%%%% ARE THESE TWO USSED???
Sexp.Vcrit=[200 5e4];
Sexp.EvelCrit=[1000 1350; 500 600];

Sexp.PHzthresh=5;
Sexp.PHvthresh=25; %vel thresh for detecting onset & offset of Ftip mvmt mm/s
Sexp.ELvthresh=[750 500]; %vel threshold for detecting the onset and end of saccade, in mm/s
Sexp.ELdisthreshmin=[15 0]; %mm dist thresh range
Sexp.ELdisthreshmax=[80 15]; %mm dist thresh range
Sexp.NthreshEL=30; %number of consecutive above or below-thresh velocities to require before criterion is passed for sac onset or offset
Sexp.NthreshPH=15;
Sexp.NbackEL=[6 6; 10 10];
Sexp.NbackPH=7;
Sexp.EthreshSD=[5 5]; %mm
Sexp.FthreshSD=[1.5];
Sexp.FprethreshSD=.35;
Sexp.ithreshF=[0 0];
Sexp.ithreshE=[1 1; 1 1];
Sexp.ELtimeout=3; %s (timeout to be certain no saccade will be made in a trial)
Sexp.Scorrdelay=.3; %wait 300 ms for any secondary/corrective saccades to occur
Sexp.tSynch=[];

%	 1: time of sample (when camera imaged eye, in milliseconds since tracker was activated)
%   12: left pupil size (arbitrary units
%   13: right pupil size (arbitrary units
%   14: left gaze position x (in pixel coordinates set by screen_pixel_coords command)
%   15: right gaze position x (pix)
%   16: left gaze position y (pix)
%   17: right gaze position y (pix)
Sexp.LRElist=[[14 16 12]' [15 17 13]'];
